### ISSUE TITLE
No functionality

### ISSUE THREAD

**Issue by JusJayD** [MrAyianaLex/streamdeck-steelseries-sonar#3]
I just download your steel series sonar plugin and I can't seem to get it to work.  Aside from .net 6.0 and the plugin for the stream deck is there anything else I need to do?

**Comment by MrAyianaLex** [comment]
Hello,
Apart from having .net 6 to install, I do not see any other prerequisite.
You have downloaded the last .streamDeckPlugin file and double-clicked it to install it ?

**Comment by JusJayD** [comment]
Yea I downloaded v1.4 which I noticed is for Sonar 52.0.0. The version of Sonar that I have is 53.0.0.  Do you think there would be that big of a difference to warrant the plugin not to work?

**Comment by MrAyianaLex** [comment]
It's not. It's work on my computer with sonar 53 ans m'y plugin on 1.4.
Are you "%appdata%\Elgato\StreamDeck\Plugins\com.mrayianalex.sonar.sdPlugin\pluginlog.log" file available ?

**Comment by JusJayD** [comment]
[pluginlog.log](https://github.com/MrAyianaLex/streamdeck-steelseries-sonar/files/13692885/pluginlog.log)

**Comment by MrAyianaLex** [comment]
The fact that the file exists means that the plugin is going well.
What makes you say that the plugin doesn't work ?
When I look at the newspaper you gave me, he says he found 11 Actions.
Since you don't have a stream deck +, you won't find them all, but you should still have the classic buttons available.

**Comment by JusJayD** [comment]
It doesn't work for me. Whenever I set up one of the buttons with an action and then test it out, it does absolutely nothing.

**Comment by MrAyianaLex** [comment]
What makes you say that buttons do nothing ?
If it's because you have Sonar open, it's normal, it doesn't update. You have to close the window and reopen it to see the updates.
If for you it's still non-functional, not seeing action in the log that you provided me, I need a more recent file that will have been produced after pressing buttons.
