### ISSUE TITLE
Can't set Output Device

### ISSUE THREAD

**Issue by Puntoboy** [MrAyianaLex/streamdeck-steelseries-sonar#4]
Trying to setup a button to change from my speakers to my headset using the Output Device Config button. When I first drag it over to the stream deck button, I can select the devices, but as soon as I deselect that button or attempt to use it, the devices disappear and the button doesn't do anything.

![image](https://github.com/MrAyianaLex/streamdeck-steelseries-sonar/assets/11718878/ac338110-aa6d-4b74-8beb-1a6b9382c4da)

**Comment by MrAyianaLex** [comment]
I'm having trouble understanding how to reproduce the bug.
Make sure to select, via a change if necessary, that all values ​​are taken into account starting from the top to the bottom.

If the problem persists, I need the file "%appdata%\Elgato\StreamDeck\Plugins\com.mrayianalex.sonar.sdPlugin\pluginlog.log" to see if there is any information in there that would help us understand the problem.

**Comment by Puntoboy** [comment]
OK, maybe I have misunderstood how Sonar works, as I'm used to Elgato WaveLink. I want to have my apps routes to different virtual inputs so I can control the volumes or each app using my Stream Deck+ easily. I also want to be able to easily swap between my speakers and my headphones. 

If Streamer mode is disabled, I have to set the output device of each virtual input. There doesn't seem to be a way with your plugin to change this device. I can use the dials to change the volumes of each of the inputs. 

![image](https://github.com/MrAyianaLex/streamdeck-steelseries-sonar/assets/11718878/59cf5358-51bb-494d-9b53-c091b9df2c17)

If Streamer mode is enabled, I have my "personal mix" and my "stream mix". I'd like a button to change the personal mix from my speakers to my headphones. However, in this mode, the input volume dials do not work so I can't change the volumes from my Stream Deck+ I have to use Sonar directly.

Maybe what I want to do isn't achievable in the current form as that's not how it's designed.

**Comment by MrAyianaLex** [comment]
Personally, I only use streamer mode, but whatever you want to do, that's exactly how I use Sonar.

I think I understand what your problem is, but it's Sonar that hasn't worked properly for several versions because I can reproduce the same bug directly from Sonar.
He no longer likes to change output devices for streamer mode

Here are my button configurations (I didn't make the bottom 4 for you, you just need to change the value in "Input device")

![sonar](https://github.com/MrAyianaLex/streamdeck-steelseries-sonar/assets/102676847/c4aec1dc-eec2-4006-9a61-d620071a51d8)

The first button configuration allows me to switch between my headphones and my speakers.

There is a bug in Sonar so I can't fix it, but changing input or output device doesn't always update.
Two solutions, close and reopen the GG application or use the second button in the configuration which allows you to change mode (Classic <-> Stream) and press it twice (I wait 2-3s before pressing a second time )

And the third button is used to adjust the volume.

But to respond, it is possible to define the device each time you exit classic mode.
first button configuration of my images, but Devic => Classic and Target => Game...
